name: .NET

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install choco packages
      run: choco install --no-progress -y winflexbison unzip curl
      
    - name: Get monetdb
      run: |
        Set-Location c:\
        curl.exe https://dev.monetdb.org/hg/MonetDB/archive/${{ env.branch }}.zip -O
        unzip.exe ${{ env.branch }}.zip
    - name: Compile and install MonetDB
      run: |
        mkdir c:\MonetDB-${{ env.branch }}\build
        Set-Location c:\MonetDB-${{ env.branch }}\build
        dir $Env:VCPKG_ROOT\scripts\buildsystems
        dir $Env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake
        cmake -G "Visual Studio 16 2019" `
          -A x64 `
          -DCMAKE_TOOLCHAIN_FILE=D:\a\MonetDBe-Python\MonetDBe-Python\vcpkg\scripts\buildsystems\vcpkg.cmake `
          -DCMAKE_INSTALL_PREFIX=C:\monetdb `
          -DTESTING=OFF `
          -DCMAKE_BUILD_TYPE=Release `
          -DASSERT=OFF `
          -DODBC=false `
          -DPY3INTEGRATION=OFF `
          -DINT128=OFF `
          ..
        cmake --build . --target ALL_BUILD --parallel 4  --config Release
        cmake --build . --target INSTALL  --config Release
    - name: Collect DLLs
      run: |
        Set-Location $GITHUB_WORKSPACE
        Copy-Item C:\monetdb\bin\bat.dll monetdbe\.
        Copy-Item C:\monetdb\bin\mapi.dll monetdbe\.
        Copy-Item C:\monetdb\bin\monetdb5.dll monetdbe\.
        Copy-Item C:\monetdb\bin\monetdbe.dll monetdbe\.
        Copy-Item C:\monetdb\bin\monetdbsql.dll monetdbe\.
        Copy-Item C:\monetdb\bin\stream.dll monetdbe\.
        ls $Env:VCPKG_ROOT\installed\x64-windows\bin\*.dll
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\libcrypto-1_1-x64.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\iconv-2.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\libxml2.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\pcre.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\zlib1.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\lzma.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\charset-1.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\bz2.dll monetdbe\.
        Copy-Item $Env:VCPKG_ROOT\installed\x64-windows\bin\libcurl.dll monetdbe\.  
    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
        #- name: Test
        #run: dotnet test --no-build --verbosity normal
